### ISSUE TITLE
How do I upgrade the new version(6.1.19)

### ISSUE THREAD

**Issue by tune6688** [LigeroSmart/docker-ligerosmart#5]
Dear  developer
Would you please let me konw how do I upgrade to the latest version (6.1.19).
I used this command to install (curl https://get.ligerosmart.com | sh).

Thank you!

**Comment by mfmatos** [comment]
Hi,

This installation script creates a folder called [ligerosmart-stack](https://github.com/LigeroSmart/ligerosmart-stack). Inside it there is a Makefile with the environment maintenance commands. 

The command below upgrades the code:

`make upgrade-core`

The command below rebuilds containers with updates from docker images

`make upgrade-containers`

The command below performs the previous two steps

`make upgrade-all`

**Comment by tune6688** [comment]
Thank you very much!
